# yillia主题参数
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: true
    content: false
    slug: false
    updated: false
    comments: true
    link: false
    permalink: false
    excerpt: false
    categories: true
    tags: true
# hexo-renderer-markdown-it插件配置
# Markdown-it config ## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    # 设置英文双引号单引号的转换为什么字符格式
    typographer: false
    quotes: '“”‘’'
  plugins:
    # 开启上下标和脚注
    - markdown-it-ins
    - markdown-it-footnote
    - markdown-it-sub
    - markdown-it-sup
    # 开启公式
    - name: '@renbaoshuo/markdown-it-katex'
      options:
        skipDelimitersCheck: false
  anchors:
    level: 2
    collisionSuffix: 'v'
    # 设置文章标题前缀
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol:  ❏
